image:
  repository: quay.io/rh-ee-jkershaw/network-operations-agent
  digest: sha256:135dab43f4ad3a001b20c5a867305d9490c67853107acc6fb800a4aaf9158cbf

route:
  enabled: true
  name: network-operations-demo

lab:
  enabled: true

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
